version: '3.7'

services:
  svelte:
    container_name: svelte
    image: svelte
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 1234:1234
    volumes:
      # Parcel needs to write 
      - ./src:/srv:rw
