version: '3.7'

services:
  svelte:
    container_name: svelte-production
    image: svelte
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 1234:1234
    volumes:
      - ./src:/srv:rw

      
